"""Reconcile what Hugo rendered with what the manifest says it rendered.

The promotion rule — a record earns a page by having prose or an image — is
implemented twice, and deliberately. Hugo decides what to render, because Hugo
is what renders. Python decides what `dist/redirects.json` says, because that is
what a future edge redirect would read. Neither can call the other.

Two implementations of one rule is the thing this repository has already had to
delete once, so it is not left on trust: this runs after a build and fails if
they disagree by a single page. Run it against a built `public/`.

    python3 tools/build.py
    hugo --minify --panicOnWarning --destination public
    python3 tools/check_stubs.py

Build it the way the publish builds it. `--minify` changes the markup this
reads.
"""

from __future__ import annotations

import json
import os
import re
import sys

from content import load, url_prefix

# A stub is the whole document: no <body>, and an instant refresh in the head.
#
# Attribute quotes are optional because the publish builds with `--minify`, which
# strips the ones it can. The first version of this matched only the unminified
# form, passed locally, and failed in CI on all 3,260 redirects — a check
# verified against a different build than the one that ships is not a check.
STUB = re.compile(
    r"""<meta\s+http-equiv=["']?refresh["']?\s+content=["']?0;\s*url=([^"'>]+)["']?""",
    re.IGNORECASE,
)


def built_pages(public: str, prefix: str) -> dict[str, str | None]:
    """Every rendered page, mapped to its refresh target or None if it is a real page."""
    out: dict[str, str | None] = {}
    for dirpath, _, filenames in os.walk(public):
        if "index.html" not in filenames:
            continue
        rel = os.path.relpath(dirpath, public).replace(os.sep, "/")
        url = prefix if rel == "." else f"{prefix}/{rel}"
        text = open(os.path.join(dirpath, "index.html"), encoding="utf-8").read()
        m = STUB.search(text)
        out[url] = m.group(1) if m else None
    return out


def main() -> int:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    public = sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, "public")
    manifest = os.path.join(root, "dist", "redirects.json")
    for path, what in ((public, "a built site"), (manifest, "dist/redirects.json")):
        if not os.path.exists(path):
            print(f"no {what} at {path}; run tools/build.py and hugo first")
            return 1

    prefix = url_prefix(root)
    pages = built_pages(public, prefix)
    records, _, _ = load(root)
    redirects = json.load(open(manifest, encoding="utf-8"))

    problems: list[str] = []

    # 1. Hugo and Python agree about which records are thin.
    hugo_stubs = {u for u, target in pages.items() if target is not None}
    said_thin = {row["from"] for row in redirects["provisional"]}
    python_thin = {r.url for r in records if not r.promoted}

    assert said_thin == python_thin, "the manifest disagrees with its own loader"

    only_hugo = (hugo_stubs & {r.url for r in records}) - python_thin
    only_python = python_thin - hugo_stubs
    for u in sorted(only_hugo):
        problems.append(f"{u}: Hugo rendered a stub, the manifest calls it promoted")
    for u in sorted(only_python):
        problems.append(f"{u}: the manifest calls it thin, Hugo rendered a full page")

    # 2. Every record has *something* at its address. A record that rendered
    #    nothing at all is a 404 the manifest promises is a redirect.
    for r in records:
        if r.url not in pages:
            problems.append(f"{r.url}: nothing was built at this address")

    # 3. Every permanent redirect the manifest names was actually generated by
    #    Hugo's aliases, and points where the manifest says.
    for row in redirects["permanent"]:
        target = pages.get(row["from"], "missing")
        if target == "missing":
            problems.append(f"{row['from']}: manifest names an alias Hugo did not build")
        elif target is None:
            problems.append(f"{row['from']}: manifest names an alias, Hugo built a real page")
        elif row["to"] not in target:
            problems.append(f"{row['from']}: redirects to {target}, manifest says {row['to']}")

    for p in problems:
        print(p)
    if problems:
        print(f"\n{len(problems)} disagreement(s) between the build and the manifest")
        return 1
    print(f"{len(pages)} pages built; {len(hugo_stubs)} redirect, "
          f"{len(records) - len(python_thin)} records have earned a page. "
          "Hugo and the manifest agree.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
